"""Type stubs for the native PlaceholderAPI core."""

from endstone import OfflinePlayer
from endstone.plugin import Plugin, Service

__all__ = ["SERVICE_NAME", "PlaceholderAPI", "__version__"]

__version__: str

SERVICE_NAME: str

class PlaceholderAPI(Service):
    """Resolves placeholders through registered expansions."""

    @property
    def active(self) -> bool: ...
    def set_placeholders(self, player: OfflinePlayer | None, text: str) -> str: ...
    def set_relational_placeholders(self, one, two, text: str) -> str: ...
    def contains_placeholders(self, text: str) -> bool: ...
    def is_registered(self, identifier: str) -> bool: ...
    @property
    def registered_identifiers(self) -> list[str]: ...
    @property
    def expansions(self) -> list: ...
    def unregister_expansion(self, owner: Plugin, identifier: str) -> bool: ...
    def unregister_expansions(self, owner: Plugin) -> int: ...

class _PapiHost:
    def start(self, plugin: Plugin) -> bool: ...
    def stop(self) -> None: ...
    @property
    def service(self) -> PlaceholderAPI | None: ...
